= http-decò

**Introduzione**

`http-decò` è una libreria Groovy pensata per semplificare al massimo l'esecuzione di richieste HTTP in questo linguaggio ed in Java. Fornisce un'API concisa e intuitiva per i metodi HTTP di base, oltre a funzionalità avanzate come retry automatici, caching delle richieste e autenticazione AWS.

**Funzionalità**

* **Metodi HTTP di base:**

```
* GET
* POST
* PUT
* DELETE
* HEAD
```

* **Metodi HTTP di facilitazione:**

```asciidoc
* POST con payload JSON
* PUT con payload JSON
* POST di tipo x-www-form-urlencoded
```

* **Decoratori:**

```asciidoc
* Retry automatico in caso di fallimento
* Cache automatica delle richieste con storage file o Redis
* Redirezione multi host
* Firma per autenticazione AWS v4
```

* **Funzionalità aggiuntive:**

```asciidoc
* Supporto alla basic authentication direttamente dalle userinfo delle URL
* Supporto nativo alle variabili d'ambiente http_proxy, https_proxy, no_proxy
* Disabilitazione semplice dei controlli HTTPS per test con certificati self-signed
* Disabilitazione semplice delle eccezioni per le richieste in errore
* Supporto lineare all'aggiunta di header nelle richieste
* Supporto lineare all'aggiunta di cookie nelle richieste
```

**Installazione**

La libreria http-decò è disponibile tramite jitpack. Per installarla, aggiungi la seguente dipendenza al tuo file `pom.xml`:

```xml
<dependency>
  <groupId>com.github.grational</groupId>
  <artifactId>http-deco</artifactId>
  <version>5.0.0</version>
</dependency>
```

**Esempio d'uso**

```groovy
import it.grational.http.request.*

// Esempio di GET request
def response = new Get("https://www.google.com").connect()

// Esempio di POST request con payload JSON
def json = [name: "John Doe", age: 30]
response = new JsonPost (
	url: "https://api.example.com/users",
	map: [
		name: 'John Doe',
		age: 30
	]
).connect()

// Esempio di utilizzo di un decoratore per il retry automatico
def response = new Retry (
	new Get("https://www.polito.it")
)

// Esempio di utilizzo di un decoratore per la cache
def response = new Cache (
	new Get("https://www.polito.it")
)
```

**Contributi**

La libreria http-decò è open source e sono graditi i contributi. Se hai trovato un bug o hai un suggerimento per migliorare la libreria, apri pure una issue sulla pagina GitHub del progetto.

**Grazie per aver utilizzato http-decò!**
