package it.italiaonline.rnd.net

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author gsus
 * @date 17-11-2016 11.14
 */
class LibrarySpec extends Specification {
	def "someLibraryMethod returns true"() {
		setup:
			Library lib = new Library()
		when:
			Boolean result = lib.someLibraryMethod()
		then:
			result == true
	}
}
